
service: apollo-lambda


plugins:
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-dotenv-plugin  

provider:
  name: aws
  runtime: nodejs16.x
  environment:
    #MONGODB_URI: ${env:MONGODB_URI}
functions:
  graphql:
    # this is formatted as <FILENAME>.<HANDLER>
    handler: src/app.graphqlHandler
    events:
    - http:
        path: /
        method: post
        cors: true
    - http:
        path: /
        method: get
        cors: true
